version: '3.9'
services:
  db:
    image: postgres:15-alpine
    container_name: postgres-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - ./data:/var/lib/postgresql/data
      # - ./mock/pagila-insert-data.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - "5432:5432"
